repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: double-quote-string-fixer
  - repo: https://gitlab.com/pycqa/flake8
    rev: ''
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear==19.8.0',  # Looks for likely bugs and design problems
          'flake8-comprehensions==3.0.1',  # Looks for unnecessary generator functions that can be converted to list comprehensions
          'flake8-deprecated==1.3',  # Looks for method deprecations
          'flake8-use-fstring==1.0',  # Enforces use of f-strings over .format and %s
          'flake8-print==3.1.4',  # Checks for print statements
          'flake8-docstrings==1.5.0',  # Verifies that all functions/methods have docstrings
          'flake8-type-annotations==0.1.0',  # Looks for misconfigured type annotations
          'flake8-annotations==1.1.1',  # Enforces type annotation
        ]
  - repo: local
    hooks:
    -   id: rst
        name: rst
        entry: rst-lint --encoding utf-8
        files: ^(CHANGELOG.rst|README.rst)$
        language: python
        additional_dependencies: [pygments, restructuredtext_lint]
  - repo: https://github.com/sondrelg/remove-query-counts
    rev: ''
    hooks:
      - id: remove-query-counts
