name: testing

on:
  push:
    branches:
      - master

jobs:
  codecov:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Test
        run: |
          poetry run coverage run manage.py test
          poetry run coverage xml
          poetry run coverage report
